add retry logic
bearyinnovative/hubot-bearychat pull request #29
Opened 2017-05-11 03:03 UTC by loddit

close #18 
断网再开后效果如下：
![image](https://cloud.githubusercontent.com/assets/394562/25930542/72719114-3639-11e7-9343-416d14566068.png)

2017-05-11 03:05 UTC, bcho commented on src/client_event.coffee
> +  EventTimeout: 'timeout'
timedout

2017-05-11 03:06 UTC, loddit commented on src/rtm_client.coffee
>      @emit EventClosed
现在观察，断网20秒后，再次重新连上网络时会触发 onWebSocketClose，这块的策略还有优化的空间。

2017-05-11 03:13 UTC, bcho requested changes

2017-05-11 03:13 UTC, bcho commented on src/rtm_client.coffee
> +      retryBackoff = 1000 * @retryTimes
这个最好用指数的

2017-05-11 03:13 UTC, bcho commented on src/rtm_client.coffee
> +        @resetRetryTimes()
这个有点问题，最好放到 connectToRTM 里面，在 ws 连上之后再 reset

2017-05-11 03:13 UTC, bcho commented on src/rtm_client.coffee
> +    @on EventClosed, @rerun.bind(@)
rerun 我觉得最好不要 subscribe 一个事件，而是在 onWebsocketClosed 里面直接进行 rerun

2017-05-11 03:13 UTC, bcho commented on src/rtm_client.coffee
> +  rerun: () ->
按照目前的写法，rerun 是可以重入的，这样可能会重复触发下面的 retry 操作。。。可能要加一个 connecting 的状态才行

2017-05-11 03:13 UTC, bcho commented on src/rtm_client.coffee
> +      setTimeout () =>
例如这里，因为 timeout 没有到，如果第二个 rerun 执行了就会重复执行这个操作了

2017-05-11 03:21 UTC, loddit commented on src/rtm_client.coffee
> +        @resetRetryTimes()
对 上一步可能不成功。

2017-05-11 03:21 UTC, loddit commented on src/rtm_client.coffee
> +    @on EventClosed, @rerun.bind(@)
我本来是这样考虑的，之后如果用利用 ping 判断掉线的逻辑，也可以用 emit EventClosed 来触发重连。 当然，也可在 ping 逻辑判断掉线后主动关闭 ws 连接，应该也能走到 onWebsocketClosed 里。

2017-05-11 08:55 UTC, bcho requested changes

2017-05-11 08:55 UTC, bcho commented on src/rtm_client.coffee
> +    @isRetrying = false
写点文档描述一下这几个 stage props 的含义吧

2017-05-11 08:55 UTC, bcho commented on src/rtm_client.coffee
> +    @isRetrying = false
isRetrying 也放到 `resetRetryTimes` 里面吧

2017-05-11 08:55 UTC, bcho commented on src/rtm_client.coffee
> +    @pingInterval = setInterval @rtmPing.bind(@), @rtmPingInterval
要不这里再判断一下，把之前可能存在的 pingInterval 也 clear 掉

2017-05-11 08:55 UTC, bcho commented on src/rtm_client.coffee
> +    @isRetrying = false
为什么这里可以设置一个 `isRetrying = false` ？另外实际的操作能放到 emit 之前吗。就是执行了实际操作了再广播这个事件可能会好点

2017-05-11 11:19 UTC, loddit commented on src/rtm_client.coffee
> +    @isRetrying = false
确实不用，我记成是如果第一次链接就没建立，不会触发 open 而直接 close。
其实都会先发一个 open 再发 close，既然会先走到 open 就不用在这里处理 isRetrying 了

2017-05-11 11:21 UTC, loddit commented on src/rtm_client.coffee
> +    @isRetrying = false
又测试了一下，如果地址本身不对比如返回 404 的话，直接触发的顺序是 error close 不会有 open。

2017-05-11 12:02 UTC, loddit commented
刚刚最后一个 commit 更完备的测试几个情况，包括一上来就没有网络，token 不对，ws 地址失效等。都会进入重连流程。

2017-05-11 12:04 UTC, loddit commented on src/rtm_client.coffee
> +    @isRetrying = false
想了想还是不放在一起了，因为都有单独使用的情况。

2017-05-12 02:06 UTC, bcho commented on src/rtm_client.coffee
> +          .catch (e) =>
这两个 catch 不能合并到一起吗？

2017-05-12 02:06 UTC, bcho commented on src/rtm_client.coffee
> +    @isRetrying = false # make sure unsuccessful connection should stop current retryflow
这个 isRetrying 的设置放到 rerun 上面。因为要进入 rerun 应该是和这个 fence 重置绑定在一起的

2017-05-12 02:06 UTC, bcho commented on src/rtm_client.coffee
> +  # a retry flow contains 3 parts: backoff waiting, ws url fetching and ws conecting.
后面可以考虑把 retry / ws / hubot 这 3 个部分拆开来写。。。不过目前先这样好了

2017-05-12 02:07 UTC, bcho commented
其他

2017-05-12 02:07 UTC, bcho commented
其他 LGTM

2017-05-12 02:19 UTC, loddit commented on src/rtm_client.coffee
> +          .catch (e) =>
如果只留最外层的 catch 无法 catch resp.json 这步里面的异常。

2017-05-12 02:21 UTC, bcho commented on src/rtm_client.coffee
> +          .catch (e) =>
不能 return resp.json() 的吗？

2017-05-12 02:22 UTC, loddit commented on src/rtm_client.coffee
> +    @isRetrying = false # make sure unsuccessful connection should stop current retryflow
意思是放往下移一行吗？

2017-05-12 02:23 UTC, bcho commented on src/rtm_client.coffee
> +    @isRetrying = false # make sure unsuccessful connection should stop current retryflow
是，和 rerun 放在一起

2017-05-12 02:56 UTC, loddit commented on src/rtm_client.coffee
> +          throw new Error("WebSocket and user data fetch failed")
为了流程清晰，主动触发异常了

2017-05-12 03:07 UTC, loddit commented on src/rtm_client.coffee
> +          .catch (e) =>
这里备忘一个我的理解错误，json() 这步本身没有抛出异常，测试中抛出异常是因为 user.name 抛出的 (之所以走到这里恰恰是因为 json() 没有抛出异常)。

2017-05-12 03:52 UTC, bcho approved these changes

2017-05-12 03:52 UTC, merged