add robot.messageRoom support
bearyinnovative/hubot-bearychat pull request #32
Opened 2017-05-26 10:03 UTC by loddit

close #21 
大致思路，首先 hubot 在 [这里](
https://github.com/github/hubot/blob/7899375f6012b7d3242efa3a9d9847a69528a898/src/robot.coffee#L562) 提供了 `messageRoom` 接口，实际上就是增加 `room` 参数并转交给 adaptor 的 `.send` 处理。

参考了其他几个 adaptor 的使用方式 `room` 可以是 `channel.vchannel_id` 或者 `channel.name`。又因为，现在 rtm_client 因为 nimnus 原因，还需要使用 to_uid / channel_id 发消息。
所以这里和 `attachments` 处理方式类似，不论是 rtm 还是 http 模式的 client，都是调用 openAPI HTTP 的 api 来实现指定讨论组转发。

至于支持使用讨论组名称做参数，目前想到可以通过多调用一次 API 实现，但可以看看有没有更好的办法。

2017-05-26 10:10 UTC, bcho commented
> 还需要使用 to_uid / channel_id 发消息。
所以这里和 attachments 处理方式类似，不论是 rtm 还是 http 模式的 client，都是调用 openAPI HTTP 的 api 来实现指定讨论组转发。

为什么 rtm 不能直接走长连接？

2017-05-26 10:14 UTC, loddit commented
rtm 发需要 to_uid 或者 channel_id 这样对使用者来说，就不是单单只知道 vchannel_id 就可以了。
而用 vchannel_id 用  openAPI 反查实现会比较费劲。

2017-05-26 10:33 UTC, bcho requested changes

2017-05-26 10:33 UTC, bcho commented on README.md
> +robot.hear /how old are you?/, (res) ->
为什么要改成正则？

2017-05-26 10:33 UTC, bcho commented on src/bearychat.coffee
> +      vchannelId = envelope.room
这个 room 的逻辑还是放到各自的 client 里面实现。然后每个 client 加一个 `sendMessageToRoom` 的方法

```
@client.sendMessageToRoom envelope.room, strings...
```

然后两个 client 里面都直接把这个 envelope.room 当作 vchannel id, 用 `bearychat.message.create` 创建好了

2017-05-26 10:36 UTC, loddit commented on README.md
> +robot.hear /how old are you?/, (res) ->
其实只支持正则 https://github.com/github/hubot/blob/master/docs/scripting.md#hearing-and-responding
之前 #30 可能就是因为文档用户用错了...

2017-05-26 10:36 UTC, bcho commented on README.md
> +robot.hear /how old are you?/, (res) ->
这个另外发 pr 改吧

2017-05-26 10:37 UTC, loddit commented on src/bearychat.coffee
> +      vchannelId = envelope.room
可以，另外 attachment 是不是也改成这种 client 分别实现？

2017-05-26 10:38 UTC, bcho commented on src/bearychat.coffee
> +      vchannelId = envelope.room
attachment 倒不用，因为是属于 adapter 自己 handle 的事件而不是实际 transport client handle 的事件。当然直接把 `_setupEvents` delegate 到各自的 client 也行。

2017-06-07 03:24 UTC, bcho commented
poke @loddit

2017-06-07 03:35 UTC, loddit commented
冲突修复

2017-06-07 03:36 UTC, bcho approved these changes
LGTM

2017-06-07 03:36 UTC, merged